name: Build Zig Game

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zig 0.14
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libx11-dev libxcursor-dev libxinerama-dev libxi-dev libgl1-mesa-dev \
            wayland-protocols

      - name: Build Game
        run: zig build -Doptimize=ReleaseFast

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Brainix-Runner-${{ matrix.os }}
          path: zig-out/bin/*

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: zig-out/bin/*
