name: Build Zig Game

on:
  push:
    tags:
      - "v*"   # runs when you push a tag like v1.0.0
  workflow_dispatch:  # allows manual run

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          zig-version: master   # or a specific version like 0.13.0

      - name: Build
        run: zig build -Drelease-fast=true

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: zig-out/bin/*

